@startuml

title __REPOSITORY's Class Diagram__\n

  namespace br.com.psytecnology {
    namespace domain.repository {
      interface br.com.psytecnology.domain.repository.ClientesRepository {
          {abstract} + findClienteFetchPedidos()
      }
    }
  }
  

  namespace br.com.psytecnology {
    namespace domain.repository {
      interface br.com.psytecnology.domain.repository.ItemPedidoRepository {
      }
    }
  }
  

  namespace br.com.psytecnology {
    namespace domain.repository {
      class br.com.psytecnology.domain.repository.JdbcClienteRepository {
          {static} - DELETE : String
          {static} - FIND_BY_NAME : String
          {static} - INSERT : String
          {static} - SELECT_ALL : String
          {static} - UPDATE : String
          - jdbcTemplate : JdbcTemplate
          + JdbcClienteRepository()
          + delete()
          + findAll()
          + findByName()
          + save()
          + update()
          - getRowMapper()
      }
    }
  }
  

  namespace br.com.psytecnology {
    namespace domain.repository {
      class br.com.psytecnology.domain.repository.JpaClienteRepository {
          - entityManager : EntityManager
          + JpaClienteRepository()
          + delete()
          + findAll()
          + findByName()
          + save()
          + update()
      }
    }
  }
  

  namespace br.com.psytecnology {
    namespace domain.repository {
      interface br.com.psytecnology.domain.repository.JpaRepositoriesClienteRepository {
          {abstract} + buscarPorNomeNativQuery()
          {abstract} + buscarPorNomeQuery()
          {abstract} + deleteByNome()
          {abstract} + deleteByNomeQuery()
          {abstract} + existsByNome()
          {abstract} + findByNomeLike()
          {abstract} + findByNomeOrId()
          {abstract} + findOneByNome()
      }
    }
  }
  

  namespace br.com.psytecnology {
    namespace domain.repository {
      interface br.com.psytecnology.domain.repository.PedidosRepository {
          {abstract} + findByCliente()
          {abstract} + findByIdFetchItens()
      }
    }
  }
  

  namespace br.com.psytecnology {
    namespace domain.repository {
      interface br.com.psytecnology.domain.repository.ProdutosRepository {
      }
    }
  }
  

  namespace br.com.psytecnology {
    namespace domain.repository {
      interface br.com.psytecnology.domain.repository.UsuarioRepository {
          {abstract} + findByNomeUsuario()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
